#!/bin/bash

echo "🚀 Task Distribution System - Free Deployment Setup"
echo "=================================================="
echo ""

echo "📋 Prerequisites Check:"
echo "1. Make sure your code is pushed to GitHub"
echo "2. Sign up for free accounts at:"
echo "   - Render.com (for hosting)"
echo "   - MongoDB Atlas (for database)"
echo ""

echo "🗄️ Step 1: MongoDB Atlas Setup"
echo "1. Go to https://www.mongodb.com/atlas"
echo "2. Create free account and cluster"
echo "3. Get your connection string"
echo "4. Add IP whitelist: 0.0.0.0/0"
echo ""

echo "🌐 Step 2: Deploy Backend to Render"
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repo"
echo "4. Configure:"
echo "   - Name: task-distribution-backend"
echo "   - Environment: Node"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "5. Add environment variables (see DEPLOYMENT_GUIDE.md)"
echo ""

echo "🎨 Step 3: Deploy Frontend to Render"
echo "1. Create another Web Service"
echo "2. Configure:"
echo "   - Name: task-distribution-frontend"
echo "   - Environment: Static Site"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm install && npm run build"
echo "   - Publish Directory: out"
echo "3. Add environment variables (see DEPLOYMENT_GUIDE.md)"
echo ""

echo "🧪 Step 4: Test Your Deployment"
echo "1. Health endpoint: https://your-backend-name.onrender.com/health"
echo "2. Frontend: https://your-frontend-name.onrender.com"
echo "3. Login: admin@example.com / admin123"
echo ""

echo "✅ Deployment files created:"
echo "- backend/render.yaml (Backend config)"
echo "- frontend/render.yaml (Frontend config)"
echo "- DEPLOYMENT_GUIDE.md (Detailed guide)"
echo ""

echo "🎯 Your app will be deployed for FREE on Render.com!"
echo "📖 See DEPLOYMENT_GUIDE.md for complete instructions"
